// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: OrionCommunication.proto

#include "OrionCommunication.pb.h"
#include "OrionCommunication.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace OrionCommunication {

static const char* OrionCommunicationService_method_names[] = {
  "/OrionCommunication.OrionCommunicationService/SetPanaromaParameters",
  "/OrionCommunication.OrionCommunicationService/GetPanaromaParameters",
  "/OrionCommunication.OrionCommunicationService/SetMotionDetectionParameters",
  "/OrionCommunication.OrionCommunicationService/GetMotionDetectionParameters",
  "/OrionCommunication.OrionCommunicationService/SetCurrentMode",
  "/OrionCommunication.OrionCommunicationService/GetCurrentMode",
  "/OrionCommunication.OrionCommunicationService/SetSensivityParameter",
  "/OrionCommunication.OrionCommunicationService/GetSensivityParameter",
  "/OrionCommunication.OrionCommunicationService/GetLastPanaromaFrame",
  "/OrionCommunication.OrionCommunicationService/GetPanaromaFrames",
  "/OrionCommunication.OrionCommunicationService/RunMotion",
  "/OrionCommunication.OrionCommunicationService/RunPanaroma",
  "/OrionCommunication.OrionCommunicationService/StopMotion",
  "/OrionCommunication.OrionCommunicationService/StopPanaroma",
  "/OrionCommunication.OrionCommunicationService/RunCalibration",
  "/OrionCommunication.OrionCommunicationService/StopCalibration",
  "/OrionCommunication.OrionCommunicationService/GetMainScreenShot",
  "/OrionCommunication.OrionCommunicationService/GetSecScreenShot",
  "/OrionCommunication.OrionCommunicationService/GotoPanaromaPixel",
  "/OrionCommunication.OrionCommunicationService/CurrentPanaromaPixel",
  "/OrionCommunication.OrionCommunicationService/SetVideoOverlay",
};

std::unique_ptr< OrionCommunicationService::Stub> OrionCommunicationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OrionCommunicationService::Stub> stub(new OrionCommunicationService::Stub(channel));
  return stub;
}

OrionCommunicationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SetPanaromaParameters_(OrionCommunicationService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPanaromaParameters_(OrionCommunicationService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetMotionDetectionParameters_(OrionCommunicationService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMotionDetectionParameters_(OrionCommunicationService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetCurrentMode_(OrionCommunicationService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCurrentMode_(OrionCommunicationService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSensivityParameter_(OrionCommunicationService_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSensivityParameter_(OrionCommunicationService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetLastPanaromaFrame_(OrionCommunicationService_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPanaromaFrames_(OrionCommunicationService_method_names[9], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_RunMotion_(OrionCommunicationService_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RunPanaroma_(OrionCommunicationService_method_names[11], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopMotion_(OrionCommunicationService_method_names[12], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopPanaroma_(OrionCommunicationService_method_names[13], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RunCalibration_(OrionCommunicationService_method_names[14], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopCalibration_(OrionCommunicationService_method_names[15], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMainScreenShot_(OrionCommunicationService_method_names[16], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSecScreenShot_(OrionCommunicationService_method_names[17], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GotoPanaromaPixel_(OrionCommunicationService_method_names[18], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CurrentPanaromaPixel_(OrionCommunicationService_method_names[19], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetVideoOverlay_(OrionCommunicationService_method_names[20], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OrionCommunicationService::Stub::SetPanaromaParameters(::grpc::ClientContext* context, const ::OrionCommunication::PanoramaPars& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetPanaromaParameters_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncSetPanaromaParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::PanoramaPars& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetPanaromaParameters_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncSetPanaromaParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::PanoramaPars& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetPanaromaParameters_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GetPanaromaParameters(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::PanoramaPars* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPanaromaParameters_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::PanoramaPars>* OrionCommunicationService::Stub::AsyncGetPanaromaParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::PanoramaPars>::Create(channel_.get(), cq, rpcmethod_GetPanaromaParameters_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::PanoramaPars>* OrionCommunicationService::Stub::PrepareAsyncGetPanaromaParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::PanoramaPars>::Create(channel_.get(), cq, rpcmethod_GetPanaromaParameters_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::SetMotionDetectionParameters(::grpc::ClientContext* context, const ::OrionCommunication::TRoi& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetMotionDetectionParameters_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncSetMotionDetectionParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::TRoi& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetMotionDetectionParameters_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncSetMotionDetectionParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::TRoi& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetMotionDetectionParameters_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GetMotionDetectionParameters(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::TRoi* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetMotionDetectionParameters_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::TRoi>* OrionCommunicationService::Stub::AsyncGetMotionDetectionParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::TRoi>::Create(channel_.get(), cq, rpcmethod_GetMotionDetectionParameters_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::TRoi>* OrionCommunicationService::Stub::PrepareAsyncGetMotionDetectionParametersRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::TRoi>::Create(channel_.get(), cq, rpcmethod_GetMotionDetectionParameters_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::SetCurrentMode(::grpc::ClientContext* context, const ::OrionCommunication::ModeQ& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetCurrentMode_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncSetCurrentModeRaw(::grpc::ClientContext* context, const ::OrionCommunication::ModeQ& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetCurrentMode_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncSetCurrentModeRaw(::grpc::ClientContext* context, const ::OrionCommunication::ModeQ& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetCurrentMode_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GetCurrentMode(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::ModeQ* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetCurrentMode_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::ModeQ>* OrionCommunicationService::Stub::AsyncGetCurrentModeRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::ModeQ>::Create(channel_.get(), cq, rpcmethod_GetCurrentMode_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::ModeQ>* OrionCommunicationService::Stub::PrepareAsyncGetCurrentModeRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::ModeQ>::Create(channel_.get(), cq, rpcmethod_GetCurrentMode_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::SetSensivityParameter(::grpc::ClientContext* context, const ::OrionCommunication::SetSensivity& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetSensivityParameter_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncSetSensivityParameterRaw(::grpc::ClientContext* context, const ::OrionCommunication::SetSensivity& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetSensivityParameter_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncSetSensivityParameterRaw(::grpc::ClientContext* context, const ::OrionCommunication::SetSensivity& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetSensivityParameter_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GetSensivityParameter(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::SetSensivity* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetSensivityParameter_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::SetSensivity>* OrionCommunicationService::Stub::AsyncGetSensivityParameterRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::SetSensivity>::Create(channel_.get(), cq, rpcmethod_GetSensivityParameter_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::SetSensivity>* OrionCommunicationService::Stub::PrepareAsyncGetSensivityParameterRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::SetSensivity>::Create(channel_.get(), cq, rpcmethod_GetSensivityParameter_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GetLastPanaromaFrame(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetLastPanaromaFrame_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncGetLastPanaromaFrameRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_GetLastPanaromaFrame_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncGetLastPanaromaFrameRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_GetLastPanaromaFrame_, context, request, false);
}

::grpc::ClientReader< ::OrionCommunication::PanoramaFrame>* OrionCommunicationService::Stub::GetPanaromaFramesRaw(::grpc::ClientContext* context, const ::OrionCommunication::FrameModeQ& request) {
  return ::grpc::internal::ClientReaderFactory< ::OrionCommunication::PanoramaFrame>::Create(channel_.get(), rpcmethod_GetPanaromaFrames_, context, request);
}

::grpc::ClientAsyncReader< ::OrionCommunication::PanoramaFrame>* OrionCommunicationService::Stub::AsyncGetPanaromaFramesRaw(::grpc::ClientContext* context, const ::OrionCommunication::FrameModeQ& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::OrionCommunication::PanoramaFrame>::Create(channel_.get(), cq, rpcmethod_GetPanaromaFrames_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::OrionCommunication::PanoramaFrame>* OrionCommunicationService::Stub::PrepareAsyncGetPanaromaFramesRaw(::grpc::ClientContext* context, const ::OrionCommunication::FrameModeQ& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::OrionCommunication::PanoramaFrame>::Create(channel_.get(), cq, rpcmethod_GetPanaromaFrames_, context, request, false, nullptr);
}

::grpc::Status OrionCommunicationService::Stub::RunMotion(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RunMotion_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncRunMotionRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_RunMotion_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncRunMotionRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_RunMotion_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::RunPanaroma(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RunPanaroma_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncRunPanaromaRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_RunPanaroma_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncRunPanaromaRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_RunPanaroma_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::StopMotion(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StopMotion_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncStopMotionRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_StopMotion_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncStopMotionRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_StopMotion_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::StopPanaroma(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StopPanaroma_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncStopPanaromaRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_StopPanaroma_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncStopPanaromaRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_StopPanaroma_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::RunCalibration(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RunCalibration_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncRunCalibrationRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_RunCalibration_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncRunCalibrationRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_RunCalibration_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::StopCalibration(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_StopCalibration_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncStopCalibrationRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_StopCalibration_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncStopCalibrationRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_StopCalibration_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GetMainScreenShot(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::ScreenFrame* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetMainScreenShot_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::ScreenFrame>* OrionCommunicationService::Stub::AsyncGetMainScreenShotRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::ScreenFrame>::Create(channel_.get(), cq, rpcmethod_GetMainScreenShot_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::ScreenFrame>* OrionCommunicationService::Stub::PrepareAsyncGetMainScreenShotRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::ScreenFrame>::Create(channel_.get(), cq, rpcmethod_GetMainScreenShot_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GetSecScreenShot(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::ScreenFrame* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetSecScreenShot_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::ScreenFrame>* OrionCommunicationService::Stub::AsyncGetSecScreenShotRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::ScreenFrame>::Create(channel_.get(), cq, rpcmethod_GetSecScreenShot_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::ScreenFrame>* OrionCommunicationService::Stub::PrepareAsyncGetSecScreenShotRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::ScreenFrame>::Create(channel_.get(), cq, rpcmethod_GetSecScreenShot_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::GotoPanaromaPixel(::grpc::ClientContext* context, const ::OrionCommunication::TPoint& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GotoPanaromaPixel_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncGotoPanaromaPixelRaw(::grpc::ClientContext* context, const ::OrionCommunication::TPoint& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_GotoPanaromaPixel_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncGotoPanaromaPixelRaw(::grpc::ClientContext* context, const ::OrionCommunication::TPoint& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_GotoPanaromaPixel_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::CurrentPanaromaPixel(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::OrionCommunication::TPoint* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CurrentPanaromaPixel_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::TPoint>* OrionCommunicationService::Stub::AsyncCurrentPanaromaPixelRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::TPoint>::Create(channel_.get(), cq, rpcmethod_CurrentPanaromaPixel_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::TPoint>* OrionCommunicationService::Stub::PrepareAsyncCurrentPanaromaPixelRaw(::grpc::ClientContext* context, const ::OrionCommunication::DummyInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::TPoint>::Create(channel_.get(), cq, rpcmethod_CurrentPanaromaPixel_, context, request, false);
}

::grpc::Status OrionCommunicationService::Stub::SetVideoOverlay(::grpc::ClientContext* context, const ::OrionCommunication::OverlayQ& request, ::OrionCommunication::AppCommandResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SetVideoOverlay_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::AsyncSetVideoOverlayRaw(::grpc::ClientContext* context, const ::OrionCommunication::OverlayQ& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetVideoOverlay_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrionCommunication::AppCommandResult>* OrionCommunicationService::Stub::PrepareAsyncSetVideoOverlayRaw(::grpc::ClientContext* context, const ::OrionCommunication::OverlayQ& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::OrionCommunication::AppCommandResult>::Create(channel_.get(), cq, rpcmethod_SetVideoOverlay_, context, request, false);
}

OrionCommunicationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::PanoramaPars, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::SetPanaromaParameters), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::PanoramaPars>(
          std::mem_fn(&OrionCommunicationService::Service::GetPanaromaParameters), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::TRoi, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::SetMotionDetectionParameters), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::TRoi>(
          std::mem_fn(&OrionCommunicationService::Service::GetMotionDetectionParameters), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::ModeQ, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::SetCurrentMode), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::ModeQ>(
          std::mem_fn(&OrionCommunicationService::Service::GetCurrentMode), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::SetSensivity, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::SetSensivityParameter), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::SetSensivity>(
          std::mem_fn(&OrionCommunicationService::Service::GetSensivityParameter), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::GetLastPanaromaFrame), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[9],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< OrionCommunicationService::Service, ::OrionCommunication::FrameModeQ, ::OrionCommunication::PanoramaFrame>(
          std::mem_fn(&OrionCommunicationService::Service::GetPanaromaFrames), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::RunMotion), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::RunPanaroma), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::StopMotion), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::StopPanaroma), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::RunCalibration), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::StopCalibration), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::ScreenFrame>(
          std::mem_fn(&OrionCommunicationService::Service::GetMainScreenShot), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::ScreenFrame>(
          std::mem_fn(&OrionCommunicationService::Service::GetSecScreenShot), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::TPoint, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::GotoPanaromaPixel), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::DummyInfo, ::OrionCommunication::TPoint>(
          std::mem_fn(&OrionCommunicationService::Service::CurrentPanaromaPixel), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrionCommunicationService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrionCommunicationService::Service, ::OrionCommunication::OverlayQ, ::OrionCommunication::AppCommandResult>(
          std::mem_fn(&OrionCommunicationService::Service::SetVideoOverlay), this)));
}

OrionCommunicationService::Service::~Service() {
}

::grpc::Status OrionCommunicationService::Service::SetPanaromaParameters(::grpc::ServerContext* context, const ::OrionCommunication::PanoramaPars* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetPanaromaParameters(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::PanoramaPars* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::SetMotionDetectionParameters(::grpc::ServerContext* context, const ::OrionCommunication::TRoi* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetMotionDetectionParameters(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::TRoi* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::SetCurrentMode(::grpc::ServerContext* context, const ::OrionCommunication::ModeQ* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetCurrentMode(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::ModeQ* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::SetSensivityParameter(::grpc::ServerContext* context, const ::OrionCommunication::SetSensivity* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetSensivityParameter(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::SetSensivity* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetLastPanaromaFrame(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetPanaromaFrames(::grpc::ServerContext* context, const ::OrionCommunication::FrameModeQ* request, ::grpc::ServerWriter< ::OrionCommunication::PanoramaFrame>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::RunMotion(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::RunPanaroma(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::StopMotion(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::StopPanaroma(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::RunCalibration(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::StopCalibration(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetMainScreenShot(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::ScreenFrame* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GetSecScreenShot(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::ScreenFrame* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::GotoPanaromaPixel(::grpc::ServerContext* context, const ::OrionCommunication::TPoint* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::CurrentPanaromaPixel(::grpc::ServerContext* context, const ::OrionCommunication::DummyInfo* request, ::OrionCommunication::TPoint* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OrionCommunicationService::Service::SetVideoOverlay(::grpc::ServerContext* context, const ::OrionCommunication::OverlayQ* request, ::OrionCommunication::AppCommandResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace OrionCommunication

